# Generated by Django 4.1.7 on 2023-04-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('disp_id', models.PositiveIntegerField(verbose_name='Диспетчер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cord_x', models.CharField(max_length=100, verbose_name='Текущее расположение по широте')),
                ('cord_y', models.CharField(max_length=100, verbose_name='Текущее расположение по высоте')),
                ('active', models.BooleanField(verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'База',
                'verbose_name_plural': 'Базы',
            },
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('oper_id', models.PositiveIntegerField(verbose_name='Оператор')),
                ('base_id', models.PositiveIntegerField(verbose_name='База')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность в полете')),
                ('on_flight', models.BooleanField(verbose_name='В полете')),
                ('cord_x', models.CharField(max_length=100, verbose_name='Текущее расположение по широте')),
                ('cord_y', models.CharField(max_length=100, verbose_name='Текущее расположение по высоте')),
                ('img_url', models.CharField(max_length=250, verbose_name='URL Изображения')),
            ],
            options={
                'verbose_name': 'БПЛА',
                'verbose_name_plural': 'БПЛА',
            },
        ),
    ]
